```{r}
# Load necessary packages
library(readr)
library(dplyr)
library(ggplot2)
```

```{r}
# Load the dataset
data <- read_csv("Input Datasets/stack_overflow_data.csv")
```
```{r}
# Question 1: Has R been growing or shrinking over time? Analyze the number of questions tagged with R each year.

# Add a percentage column
data_percentage <- data %>%
  mutate(percentage = (num_questions / year_total) * 100)

# Filter for R tags
r_over_time <- data_percentage %>%
  filter(tag == "r")

print(r_over_time)
```
```{r}
# Bonus: create a line plot of percentage over time
ggplot(r_over_time) +
  geom_line(aes(x = year, y = percentage))
```
```{r}
# Question 2: What percentage of the total number of questions asked in 2020 had the R tag?

# Filter for R tags in 2020
R_tag_2020 <- data_percentage %>% 
  filter(tag == "r", year == "2020")

# Select the percentage column
r_selected <- R_tag_2020 %>% select(percentage)

# Save as a numeric variable
r_percentage <- r_selected$percentage
r_percentage
```
```{r}
# Question 3: What were the five most asked-about tags between 2015-2020?

# Find total number of questions for each tag in the period 2015-2020
sorted_tags <- data %>%
  filter(year >= 2015) %>% 
  group_by(tag) %>% 
  summarize(tag_total = sum(num_questions)) %>% 
  arrange(desc(tag_total))

# Get the five largest tags
highest_tags <- head(sorted_tags$tag, n = 5)

print(highest_tags)
```
```{r}
# Bonus: Visualize your answer
#Filter for the five largest tags
data_subset <- data_percentage %>%
   filter(tag %in% highest_tags, year >= 2015)

# Plot tags over time on a line plot using color to represent tag
ggplot(data_subset, aes(x = year, y = percentage, color = tag)) +
  geom_line()
```