---
title: "Original Solution"
output: html_document
---

```{r}
# Import required packages
library(dplyr)
library(readr)
```

```{r}
# Load the data
flights <- read_csv("Input Datasets/flights2022-h2.csv")
airlines <- read_csv("Input Datasets/airlines.csv")
airports <- read_csv("Input Datasets/airports.csv")
```
```{r}
# Join the flights, airlines, and airports data frames together
complex_join <- flights %>%
  left_join(airlines, by = "carrier") %>%
  rename(airline_name = name) %>% 
  left_join(airports, by = c("dest" = "faa")) %>% 
  rename(airport_name = name)
```

```{r}
# Find flight duration in hours
transformed_data <- complex_join %>%
  mutate(flight_duration = air_time / 60)
```

```{r}
# Determine the average flight duration and number of flights for each airline and airport combination
analysis_result <- transformed_data %>%
  group_by(airline_name, airport_name) %>%
  summarize(avg_flight_duration = mean(flight_duration, na.rm = TRUE),
            count = n()) %>%
  ungroup()

analysis_result
```
```{r}
# From which airline and to which city do the most flights from NYC go to?
frequent <- analysis_result %>% 
  arrange(desc(count)) %>% 
  head(1)

frequent
```
```{r}
# Which airline and to which airport has the longest average flight duration (in hours) from NYC?
longest <- analysis_result %>% 
  arrange(desc(avg_flight_duration)) %>% 
  head(1)

longest
```
```{r}
# What was the least common destination airport departing from JFK?
transformed_data %>% 
  filter(origin == "JFK") %>% 
  group_by(airport_name) %>% 
  summarize(count = n()) %>% 
  arrange(count)

least <- "Eagle County Regional Airport"

transformed_data
least
```